quantum-meachanics/holdup-spring

- src/main/java/com/quantum/holdup/domain/entity/Reservation.java
- src/main/java/com/quantum/holdup/domain/entity/Space.java
공간 엔티티
-address 속성 추가
-Member 변수명 owner로 변경
예약 엔티티
- 불필요한 설명 속성 삭제 Member 변수명 client로 변경
> 공간, 예약 엔티티 수정

- src/main/java/com/quantum/holdup/config/WebSecurityConfig.java
- src/main/java/com/quantum/holdup/controller/ReportController.java
- src/main/java/com/quantum/holdup/domain/dto/CreateMemberDTO.java
- src/main/java/com/quantum/holdup/domain/dto/MemberDTO.java
- src/main/java/com/quantum/holdup/domain/entity/Member.java
- src/main/java/com/quantum/holdup/filter/JwtAuthorizationFilter.java
- src/main/java/com/quantum/holdup/filter/JwtPostAuthorizationFilter.java
- src/main/java/com/quantum/holdup/service/MemberService.java
- fix Member 에 address 주소를 추가하였습니다.
- fix 게시글 에서 사용자의 토큰을 인증합니다. 
- JWT 게시글 필터를 추가하여 게시글을 작성하는 사용자에 대한 토큰 과 권한을 인증합니다.
> [FIX] Member / JWT

- src/main/java/com/quantum/holdup/domain/entity/Report.java
- src/main/java/com/quantum/holdup/service/ReportService.java
게시글 을 생성하는 메서드에 정보가 담기지 않았습니다.
그래서 메서드에 계정정보를 담을 수 있게 수정하였습니다.
> - fix Report 에 Member 정보가 담기지 않는것을 추가하였습니다. commitmit

- src/main/java/com/quantum/holdup/common/AuthConstants.java
- src/main/java/com/quantum/holdup/config/SwaggerConfig.java
- src/main/java/com/quantum/holdup/config/WebConfig.java
- src/main/java/com/quantum/holdup/config/WebSecurityConfig.java
- src/main/java/com/quantum/holdup/controller/ReservationController.java
- src/main/java/com/quantum/holdup/controller/SpaceController.java
- src/main/java/com/quantum/holdup/domain/dto/CreateReservationDTO.java
- src/main/java/com/quantum/holdup/domain/dto/CreateSpaceDTO.java
- src/main/java/com/quantum/holdup/domain/entity/Reservation.java
- src/main/java/com/quantum/holdup/domain/entity/Space.java
- src/main/java/com/quantum/holdup/filter/CustomAuthenticationFilter.java
- src/main/java/com/quantum/holdup/filter/HeaderFilter.java
- src/main/java/com/quantum/holdup/filter/JwtAuthorizationFilter.java
- src/main/java/com/quantum/holdup/filter/JwtPostAuthorizationFilter.java
- src/main/java/com/quantum/holdup/handler/CustomAuthFailUserHandler.java
- src/main/java/com/quantum/holdup/handler/CustomAuthSuccessHandler.java
- src/main/java/com/quantum/holdup/handler/CustomAuthenticationProvider.java
- src/main/java/com/quantum/holdup/service/CustomUserDetailService.java
- src/main/java/com/quantum/holdup/service/MemberService.java
- src/main/java/com/quantum/holdup/service/ReportService.java
- src/main/java/com/quantum/holdup/service/ReservationService.java
- src/main/java/com/quantum/holdup/service/SpaceService.java
- src/main/java/com/quantum/holdup/util/ConvertUtil.java
- src/main/java/com/quantum/holdup/util/TokenUtils.java
* 예약 신청 기능 구현
* JWT 파일들 가독성 개선
> 예약 신청 기능 및 가독성 개선

- src/main/java/com/quantum/holdup/controller/ReportController.java
- src/main/java/com/quantum/holdup/domain/dto/CreateReportDTO.java
- src/main/java/com/quantum/holdup/domain/dto/ReportDTO.java
- src/main/java/com/quantum/holdup/domain/entity/Report.java
- src/main/java/com/quantum/holdup/repository/ReportRepository.java
- src/main/java/com/quantum/holdup/service/ReportService.java
- 수정부분 수정
- 전체조회부분 수정
- 필요없는 임포트 삭제 정렬
> 신고 crud문 수정

- src/main/java/com/quantum/holdup/config/WebSecurityConfig.java
- src/main/java/com/quantum/holdup/controller/MemberController.java
- src/main/java/com/quantum/holdup/domain/dto/ReportDTO.java
- src/main/java/com/quantum/holdup/domain/dto/SearchMemberEmailDTO.java
- src/main/java/com/quantum/holdup/filter/JwtAuthorizationFilter.java
- src/main/java/com/quantum/holdup/repository/MemberRepository.java
- src/main/java/com/quantum/holdup/service/MemberService.java
- 입력하면 사용자의 이메일을 찾을 수 있는 기능 
- 정상적으로 작동하는것을 확인하였습니다.
- commit
> - feature 사용자의 이름 과 전화번호를

- src/main/java/com/quantum/holdup/config/WebConfig.java
- src/main/java/com/quantum/holdup/config/WebSecurityConfig.java
- src/main/java/com/quantum/holdup/controller/MemberController.java
- src/main/java/com/quantum/holdup/domain/dto/LoginMemberDTO.java
- src/main/java/com/quantum/holdup/filter/JwtAuthorizationFilter.java
- src/main/java/com/quantum/holdup/handler/CustomAuthSuccessHandler.java
> Feature/예약 crud문 작성

- src/main/java/com/quantum/holdup/controller/MemberController.java
- src/main/java/com/quantum/holdup/service/MemberService.java
final 키워드 누락된 부분 추가
EmailService 컴파일에러는 yml파일 수정해주면 해결됨
> 멤버 서비스, 컨트롤러 컴파일 에러 해결

- src/main/java/com/quantum/holdup/controller/InquiryController.java
- src/main/java/com/quantum/holdup/controller/ReportController.java
- src/main/java/com/quantum/holdup/controller/ReviewController.java
- src/main/java/com/quantum/holdup/domain/dto/CommentDTO.java
- src/main/java/com/quantum/holdup/domain/entity/Comment.java
- src/main/java/com/quantum/holdup/repository/ReportRepository.java
- src/main/java/com/quantum/holdup/service/CommentService.java
- src/main/java/com/quantum/holdup/service/InquiryService.java
- src/main/java/com/quantum/holdup/service/ReportService.java
- 신고, 리뷰에 댓글 기능 추가
- 신고, 문의 서비스클래스에 변수명 수정
> 신고, 리뷰 게시글에 댓글 추가

- src/main/java/com/quantum/holdup/controller/EmailController.java
- src/main/java/com/quantum/holdup/controller/PasswordResetController.java
- src/main/java/com/quantum/holdup/domain/dto/PasswordResetRequestDTO.java
- src/main/java/com/quantum/holdup/domain/dto/VerificationRequestDTO.java
- src/main/java/com/quantum/holdup/domain/entity/Member.java
- src/main/java/com/quantum/holdup/handler/CustomAuthSuccessHandler.java
- src/main/java/com/quantum/holdup/repository/MemberRepository.java
- src/main/java/com/quantum/holdup/service/EmailService.java
- src/main/java/com/quantum/holdup/service/PasswordResetService.java
정상적인 작동은 확인하지 못 하였지만
일단 실행했을때 오류는 없기 때문에 push 먼저 합니다.
> Feature/이메일 인증을 통한 비밀번호 변경

- src/main/java/com/quantum/holdup/controller/InquiryController.java
- src/main/java/com/quantum/holdup/controller/ReportController.java
- src/main/java/com/quantum/holdup/controller/ReviewController.java
- src/main/java/com/quantum/holdup/domain/dto/CommentDTO.java
- src/main/java/com/quantum/holdup/domain/dto/CreateInquiryDTO.java
- src/main/java/com/quantum/holdup/domain/dto/CreateReportDTO.java
- src/main/java/com/quantum/holdup/domain/dto/CreateReviewDTO.java
- src/main/java/com/quantum/holdup/service/CommentService.java
- src/main/java/com/quantum/holdup/service/InquiryService.java
- src/main/java/com/quantum/holdup/service/ReportService.java
- src/main/java/com/quantum/holdup/service/ReviewService.java
- 댓글부분 url에 게시글 번호 추가하여 오류 나지 않게 수정(컨트롤러, 서비스, DTO 수정)
- 리뷰 서비스에 리뷰추가 메서드 반환값 수정
- 서비스 수정하면서 각각의 createDTO 필드값 수정
> 댓글 부분 수정, 리뷰.문의.신고 서비스 수정

- src/main/java/com/quantum/holdup/domain/dto/CreateSpaceDTO.java
- src/main/java/com/quantum/holdup/domain/entity/Space.java
- src/main/java/com/quantum/holdup/service/SpaceService.java
> 공간 엔티티 속성 수정

- src/main/java/com/quantum/holdup/config/WebSecurityConfig.java
- src/main/java/com/quantum/holdup/controller/MemberController.java
- src/main/java/com/quantum/holdup/domain/dto/CreateMemberDTO.java
- src/main/java/com/quantum/holdup/filter/JwtAuthorizationFilter.java
- src/main/java/com/quantum/holdup/repository/MemberRepository.java
- src/main/java/com/quantum/holdup/service/MemberService.java
- 닉네임 과 이메일을 중복체크
- url 예외처리
- repository sql 문 추가 commit
> [FIX]  Signup 프론트 연결을 위한 수정

- src/main/java/com/quantum/holdup/domain/dto/ReviewDTO.java
- src/main/java/com/quantum/holdup/service/ReviewService.java
- 조회되는 필드 변경하여 dto와 서비스 부분 수정(날짜와 닉네임부분 추가)
> 리뷰 전체 조회 필드 수정

- src/main/java/com/quantum/holdup/controller/ReviewController.java
- src/main/java/com/quantum/holdup/service/ReviewService.java
> 리뷰 게시글 상세페이지 추가

- build.gradle
- src/main/java/com/quantum/holdup/config/AwsS3Config.java
- src/main/java/com/quantum/holdup/config/SwaggerConfig.java
- src/main/java/com/quantum/holdup/config/WebSecurityConfig.java
- src/main/java/com/quantum/holdup/controller/ReviewController.java
- src/main/java/com/quantum/holdup/domain/dto/CreateReviewDTO.java
- src/main/java/com/quantum/holdup/domain/entity/Image.java
- src/main/java/com/quantum/holdup/domain/entity/Review.java
- src/main/java/com/quantum/holdup/service/ReservationService.java
- src/main/java/com/quantum/holdup/service/ReviewService.java
- src/main/java/com/quantum/holdup/service/S3Service.java
- src/main/java/com/quantum/holdup/service/SpaceService.java
- SpaceService 이멜이 가져오기 안되서 임시 처리
- SwaggerConfig에 토큰 추가 헤더 추가
- amazons3 이용해서 이미지업로드 기능 추가(s3config s3service생성, ReviewService 내용 추가, ReviewController 내용 추가(임시 추가)
> 리뷰 게시글 추가에 사진 업로드 추가(안되는거 임시 처리)

- src/main/java/com/quantum/holdup/service/ReservationService.java
- src/main/java/com/quantum/holdup/service/ReviewService.java
- src/main/java/com/quantum/holdup/service/SpaceService.java
> 오타 수정 및 불필요한 임포트 삭제

- src/main/java/com/quantum/holdup/config/WebSecurityConfig.java
- src/main/java/com/quantum/holdup/controller/EmailController.java
- src/main/java/com/quantum/holdup/controller/MemberController.java
- src/main/java/com/quantum/holdup/domain/dto/CreateMemberDTO.java
- src/main/java/com/quantum/holdup/domain/dto/VerificationDTO.java
- src/main/java/com/quantum/holdup/domain/entity/VerificationCode.java
- src/main/java/com/quantum/holdup/filter/JwtAuthorizationFilter.java
- src/main/java/com/quantum/holdup/repository/VerificationCodeRepository.java
- src/main/java/com/quantum/holdup/service/EmailService.java
- src/main/java/com/quantum/holdup/service/MemberService.java
- 비회원 이메일 인증구현
- 인증시 인증번호는 삭제됨
- 회원가입이 정상적으로 작동
> [FIX] singup login 백엔드 수정

- src/main/java/com/quantum/holdup/controller/ReviewController.java
- src/main/java/com/quantum/holdup/domain/dto/CreateReviewDTO.java
- src/main/java/com/quantum/holdup/service/ReviewService.java
- dto에 images 추가
- 필요없는 import 삭제
> 리뷰 게시글 이미지 업로드 부분 수정

- src/main/java/com/quantum/holdup/controller/SpaceController.java
- src/main/java/com/quantum/holdup/domain/dto/CreateSpaceDTO.java
- src/main/java/com/quantum/holdup/service/SpaceService.java
> 공간에 사진 첨부 기능 수정

- src/main/java/com/quantum/holdup/controller/ReviewController.java
- src/main/java/com/quantum/holdup/domain/dto/CreateReviewDTO.java
- src/main/java/com/quantum/holdup/domain/entity/ReviewImage.java
- src/main/java/com/quantum/holdup/service/ReviewService.java
- src/main/java/com/quantum/holdup/service/S3Service.java
- S3Service url리턴으로 수정
- ReviewImage엔티티에 imageName 추가
- ReviewService에 url에서 이미지 name 추출 메소드 추가, ReviewService 수정
- CreateReviewDTO 에 images 삭제
> 리뷰 게시글 이미지 업로드 추가 수정

- build.gradle
- src/main/java/com/quantum/holdup/controller/MemberController.java
- src/main/java/com/quantum/holdup/domain/dto/MemberDTO.java
- src/main/java/com/quantum/holdup/domain/dto/UpdateMemberDTO.java
- src/main/java/com/quantum/holdup/domain/entity/Member.java
- src/main/java/com/quantum/holdup/service/CustomUserDetails.java
- src/main/java/com/quantum/holdup/service/MemberService.java
- feature
- - 프론트 와의 연동
- CustomUserDetails 수정
- UpdateMemberDTO 추가
- MemberEntity 수정
- Member 정보 수정 기능
commit
> Feature/mypage 백엔드

- src/main/java/com/quantum/holdup/config/WebSecurityConfig.java
- src/main/java/com/quantum/holdup/controller/MemberController.java
- src/main/java/com/quantum/holdup/domain/dto/CreateMemberDTO.java
- src/main/java/com/quantum/holdup/domain/dto/PasswordCheckRequestDTO.java
- src/main/java/com/quantum/holdup/domain/dto/UpdateMemberDTO.java
- src/main/java/com/quantum/holdup/domain/entity/Member.java
- src/main/java/com/quantum/holdup/service/MemberService.java
- 회원정보 수정 기능
- CreateMemberDTO 수정 addressDetail 추가
- UpdateMemberDTO 수정 addressDetail 추가
- MemberEntity 수정 addressDetail 추가
- Member 정보 수정 기능 
- MemberService 수정 저장로직 수정
- 프론트 와 연동
- 정상적으로 회원정보가 수정 확인
> [Feature] mypage 백엔드

- src/main/java/com/quantum/holdup/controller/MemberController.java
- src/main/java/com/quantum/holdup/domain/dto/RechargeCreditsDTO.java
- src/main/java/com/quantum/holdup/domain/dto/UpdateMemberDTO.java
- src/main/java/com/quantum/holdup/domain/entity/Member.java
- src/main/java/com/quantum/holdup/repository/MemberRepository.java
- src/main/java/com/quantum/holdup/service/MemberService.java
- feature
- MemberRepository 수정 Optional<Member>
- MemberController @PutMapping("/{email}/recharge-credits") rechargeCredits 메서드 추가 (크레딧 충전)
- Member @Builder 에서 관리하던 크레딧 수정
- MemberService 수정 rechargeCredits 메서드 추가 (크레딧 충전) commit
> [FEATURE] MYPage - Credit 

- src/main/java/com/quantum/holdup/controller/ReportController.java
- src/main/java/com/quantum/holdup/controller/ReviewController.java
- src/main/java/com/quantum/holdup/domain/dto/CommentDTO.java
- src/main/java/com/quantum/holdup/domain/dto/ReviewCommentDTO.java
- src/main/java/com/quantum/holdup/repository/CommentRepository.java
- src/main/java/com/quantum/holdup/repository/ReportRepository.java
- src/main/java/com/quantum/holdup/service/CommentService.java
- 댓글 조회기능 추가
- 댓글 추가기능 코드 수정
- commentDTO -> ReviewCommentDTO 로 변경
> 댓글 목록 조회 기능

- src/main/java/com/quantum/holdup/controller/InquiryController.java
- src/main/java/com/quantum/holdup/domain/dto/InquiryDTO.java
- src/main/java/com/quantum/holdup/service/InquiryService.java
- 검색기능 주석
- inquiryDto에 createdate추가
> 문의 게시글 전체조회 수정

- src/main/java/com/quantum/holdup/controller/InquiryController.java
- src/main/java/com/quantum/holdup/domain/dto/CreateInquiryDTO.java
- src/main/java/com/quantum/holdup/domain/entity/InquiryImage.java
- src/main/java/com/quantum/holdup/repository/InquiryImageRepository.java
- src/main/java/com/quantum/holdup/service/InquiryService.java
- CreateInquiryDTO에 nickname 추가
- service에 이미지 추가 코드 추가
- InquiryImage 엔티티 추가
> 문의 게시글 이미지 추가 기능

- src/main/java/com/quantum/holdup/controller/InquiryController.java
- src/main/java/com/quantum/holdup/domain/dto/InquiryDetailDTO.java
- src/main/java/com/quantum/holdup/repository/InquiryImageRepository.java
- src/main/java/com/quantum/holdup/service/InquiryService.java
- controlloer와 sevice에 메서드 추가
- InquiryDetailDTO 추가
- 상세페이지 내용에 이미지 추가
> 문의 게시글에 상세페이지

- src/main/java/com/quantum/holdup/controller/InquiryController.java
- src/main/java/com/quantum/holdup/domain/entity/Inquiry.java
- src/main/java/com/quantum/holdup/service/InquiryService.java
- 이미지 추가
- 이미지 삭제 기능 추가
- member nullpointexception으로 멤버찾는 코드 추가
> 문의 게시글 수정부분 수정

- src/main/java/com/quantum/holdup/controller/ReportController.java
- src/main/java/com/quantum/holdup/domain/dto/ReportDTO.java
- src/main/java/com/quantum/holdup/service/ReportService.java
- 컨트롤러에 닉네임으로 찾기 주석
- ReportService return에 createDate 추가
- ReportDTO에 createDate추가
> 신고 게시글 전체조회 수정

- src/main/java/com/quantum/holdup/controller/ReportController.java
- src/main/java/com/quantum/holdup/domain/dto/CreateReportDTO.java
- src/main/java/com/quantum/holdup/domain/entity/ReportImage.java
- src/main/java/com/quantum/holdup/repository/ReportImageRepository.java
- src/main/java/com/quantum/holdup/service/ReportService.java
- 컨트롤러에 이미지 넣을수 있게 변경
- 서비스 메서드도 이미지 추가할수 있게 변경
- ReportImage 엔티티 추가
- CreateReportDTO에 nickname추가, 생성자 추가
- ReportImageRepository 추가
> 신고 게시글 추가페이지에 이미지 넣을수 있게 수정

- src/main/java/com/quantum/holdup/controller/ReportController.java
- src/main/java/com/quantum/holdup/domain/dto/ReportDetailDTO.java
- src/main/java/com/quantum/holdup/repository/ReportImageRepository.java
- src/main/java/com/quantum/holdup/service/ReportService.java
- 컨트롤러에 DTO 수정
- 서비스에 이미지추가 코드 추가
- ReportDetailDTO 추가
- ReportImageRepository 코드 추가
> 신고 게시글 상세페이지에 이미지 추가할수 있게 수정

- src/main/java/com/quantum/holdup/controller/ReportController.java
- src/main/java/com/quantum/holdup/service/ReportService.java
- 컨트롤러 이미지 넣을수 잇게 수정
- 서비스 이미지 삭제, 새이미지 추가 코드 추가
> 신고 게시글 수정페이지 이미지 수정 가능하게 수정

- src/main/java/com/quantum/holdup/controller/ReportController.java
- src/main/java/com/quantum/holdup/domain/dto/ReportCommentDTO.java
- src/main/java/com/quantum/holdup/repository/CommentRepository.java
- src/main/java/com/quantum/holdup/service/CommentService.java
- CommentRepository에 코드 추가
- service에 메서드 추가
- ReportCommentDTO 추가
- ReportController에 조회 메서드 추가
> 신고 게시글 상세피이지에서 댓글 조회 추가

- src/main/java/com/quantum/holdup/controller/ReportController.java
- src/main/java/com/quantum/holdup/controller/ReviewController.java
- src/main/java/com/quantum/holdup/domain/entity/Inquiry.java
- src/main/java/com/quantum/holdup/domain/entity/Report.java
- src/main/java/com/quantum/holdup/domain/entity/Review.java
- src/main/java/com/quantum/holdup/service/InquiryService.java
- src/main/java/com/quantum/holdup/service/ReportService.java
- src/main/java/com/quantum/holdup/service/ReviewService.java
- 각 게시글 엔티티 생성자에 createDate추가
- 서비스 메서드에도 createDate 추가
- ReportController 수정 메서드에 사진을 꼭 추가 하지 않아도 작성할 수 있게 수정
- ReviewController 수정 메서드에 사진을 꼭 추가 하지 않아도 작성할 수 있게 수정
- ReviewService에 이미지가 없으면 상세페이지 내용이 안나와 해당 코드 주석
> 게시글 수정하면 날짜 안나오는거 수정

- src/main/java/com/quantum/holdup/controller/AdminController.java
- src/main/java/com/quantum/holdup/controller/MemberController.java
- src/main/java/com/quantum/holdup/domain/dto/MemberDTO.java
- src/main/java/com/quantum/holdup/repository/MemberRepository.java
- src/main/java/com/quantum/holdup/service/AdminMemberService.java
- src/main/java/com/quantum/holdup/service/MemberService.java
- AdminMemberService 회원 정보 관리 / 조회
- AdminController 회원 정보 관리 / 조회
- MemberController 회원 목록 조회 기능 삭제
- MemberService 회원 목록 조회 기능 삭제
- MemberRepository 사용하지 않는 코드 삭제
commit
> [Feature] 관리자 페이지

- src/main/java/com/quantum/holdup/controller/ReviewController.java
- src/main/java/com/quantum/holdup/domain/dto/ReservationListDTO.java
- src/main/java/com/quantum/holdup/repository/ReviewRepository.java
- src/main/java/com/quantum/holdup/service/ReservationService.java
- src/main/java/com/quantum/holdup/service/ReviewService.java
> 리뷰 작성 예약 아이디 가져와서 작성할수 있게 수정

- src/main/java/com/quantum/holdup/controller/InquiryController.java
- src/main/java/com/quantum/holdup/controller/ReviewController.java
- src/main/java/com/quantum/holdup/repository/CommentRepository.java
- src/main/java/com/quantum/holdup/repository/InquiryImageRepository.java
- src/main/java/com/quantum/holdup/repository/ReviewImageRepository.java
- src/main/java/com/quantum/holdup/repository/ReviewRepository.java
- src/main/java/com/quantum/holdup/service/CommentService.java
- src/main/java/com/quantum/holdup/service/InquiryService.java
- src/main/java/com/quantum/holdup/service/ReviewService.java
- 리뷰글을 삭제할때 댓글과 이미지가 있으면 둘다 같이 삭제 할 수 있게 코드 수정
- 문의글도 이미지가 있으면 같이 삭제될수 있게 수정
- repository에 삭제할수있는 메소드 추가
> Fix/게시글 삭제 기능 수정

- src/main/java/com/quantum/holdup/service/InquiryService.java
- 문의 게시글만 닉네임이 로그인한 사용자 닉네임으로 되어있어서 그것만 수정
> 게시글 수정삭제 글쓴이만 할 수 있게 수정
